services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/products.json:/usr/src/app/products.json

  admin:
    build:
      context: ./admin-panel
    ports:
      - "8080:8080"
    volumes:
      - ./backend/products.json:/usr/src/app/products.json